Module 1 tasks 2,3,4,5 are complited
js-tasks-ru/jsbasic-20230529_stanislav-osipkin pull request #3
Opened 2023-06-05 15:32 UTC by StanleyOspin

2023-06-05 15:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-06 05:14 UTC, koalex requested changes

2023-06-06 05:14 UTC, koalex commented on 1-module/4-task/index.js
> +  if (str.toLowerCase().includes('1xbet') || str.toLowerCase().includes('xxx')) {
Можно так:
`return str.toLowerCase().includes('1xbet') || str.toLowerCase().includes('xxx');`

2023-06-06 05:14 UTC, koalex commented on 1-module/2-task/index.js
> +  } else if (name.length > name.trim().length) {
Должно быть
`else if (name.includes(' '))`

2023-06-06 05:21 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-06-06 05:23 UTC, StanleyOspin commented on 1-module/4-task/index.js
> +  if (str.toLowerCase().includes('1xbet') || str.toLowerCase().includes('xxx')) {
Исправить код?

2023-06-06 07:42 UTC, koalex approved these changes

2023-06-06 07:42 UTC, merged